In [2]:
import numpy as np

In [3]:
# 3-dimensional

arr3D = np.array([[[1, 2,],[3, 4],[5, 6]],[[7, 8],[9, 10],[11, 12]]]) # 2 x 3 x 2
print(arr3D, arr3D.shape)

# indexing
print(arr3D[0, 1, 1])

# slicing
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first col from both layers

arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
