In [1]:
import numpy as np

In [17]:
# Create
arr1 = np.zeros((2, 3), dtype = "int64") # prefill
print(arr1, arr1.shape)

arr2 = np.ones((4,), dtype = "int64") # prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 9) # prefill with value
print(arr3, arr3.shape)

arr4 = np.eye((4), dtype = "int64") # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 10, 2) # range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1] (4,)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]] (3, 4)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] (4, 4)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)
