In [1]:
import numpy as np

In [3]:
# fancy indexing 
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [7]:
# boolean indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]
